### ISSUE TITLE
Xcode新版本变异报错，恢复老的libtolua.a之后正常

### ISSUE THREAD

**Issue by zsmhunter** [jarjin/LuaFramework_UGUI_V2#19]
Undefined symbols for architecture arm64:
  "_luaL_typerror", referenced from:
      _class_new_event in libtolua.a(tolua-4fdd60e5a983f0d51403d8d2bcca4a4cae808a71e9a25a883e308baf21daefe6.o)
      _tolua_initsettable in libtolua.a(tolua-4fdd60e5a983f0d51403d8d2bcca4a4cae808a71e9a25a883e308baf21daefe6.o)
      _tolua_initgettable in libtolua.a(tolua-4fdd60e5a983f0d51403d8d2bcca4a4cae808a71e9a25a883e308baf21daefe6.o)
      __long in libtolua.a(int64.o)
      __int64tostring in libtolua.a(int64.o)
      __int64tonum2 in libtolua.a(int64.o)
      _tolua_checkint64 in libtolua.a(int64.o)
      ...
     (maybe you meant: _LuaDLL_luaL_typerror_m495D9A5771C1814ABDFDB1C4EEA3DCD82BFAA08A, _LuaDLL_luaL_typerror_m495D9A5771C1814ABDFDB1C4EEA3DCD82BFAA08A_MetadataUsageId )
  "_lua_tointegerx", referenced from:
      _encode in libtolua.a(lsproto.o)

**Comment by crater-xx** [comment]
遇到了同样的问题

**Comment by wanxing** [comment]
libtolua.a文件可以共享一下吗?

**Comment by huijian142857** [comment]
> libtolua.a文件可以共享一下吗?

可以用老版 LuaFramework_UGUI 这个项目里面的

**Comment by huijian142857** [comment]
@jarjin 请解决下这个严重的编译错误

**Comment by yangguanghenqing** [comment]
遇到同样的问题，同样的编译错误。是因为xcode版本的问题吗？@jarjin 关注下吧

**Comment by yangguanghenqing** [comment]
> Undefined symbols for architecture arm64:
> "_luaL_typerror", referenced from:
> _class_new_event in libtolua.a(tolua-4fdd60e5a983f0d51403d8d2bcca4a4cae808a71e9a25a883e308baf21daefe6.o)
> _tolua_initsettable in libtolua.a(tolua-4fdd60e5a983f0d51403d8d2bcca4a4cae808a71e9a25a883e308baf21daefe6.o)
> _tolua_initgettable in libtolua.a(tolua-4fdd60e5a983f0d51403d8d2bcca4a4cae808a71e9a25a883e308baf21daefe6.o)
> __long in libtolua.a(int64.o)
> __int64tostring in libtolua.a(int64.o)
> __int64tonum2 in libtolua.a(int64.o)
> _tolua_checkint64 in libtolua.a(int64.o)
> ...
> (maybe you meant: _LuaDLL_luaL_typerror_m495D9A5771C1814ABDFDB1C4EEA3DCD82BFAA08A, _LuaDLL_luaL_typerror_m495D9A5771C1814ABDFDB1C4EEA3DCD82BFAA08A_MetadataUsageId )
> "_lua_tointegerx", referenced from:
> _encode in libtolua.a(lsproto.o)

这个问题怎么修复的啊

**Comment by jarjin** [comment]
加下微信群，单反一个版本

**Comment by yangguanghenqing** [comment]
求微信或微信群

**Comment by jarjin** [comment]
jarjin

**Comment by jarjin** [comment]
更新即可
