### ISSUE TITLE
App Store 审核不通过

### ISSUE THREAD

**Issue by KuFei** [jarjin/LuaFramework_UGUI_V2#35]
给公司的unity游戏用了LuaFramework_UGUI_V2后，提交App Store 审核不通过，lua脚本和资源都打进了ipa包里审核期间并没有下载任何lua脚本的，官方有人知道怎么解决吗
Guideline 2.5.2 -Performance -Software Requirements
During review, we still found that your app downloaded code, as part of the app launch sequence, including support for remote luascript retrieval, which is not permitted on the App Store.

**Comment by jarjin** [comment]
这不是写的很明白，你下载了lua脚本。

**Comment by KuFei** [comment]
没有下载的，机审就被打回来了

**Comment by jarjin** [comment]
做代码混淆么？C#的  没有的话做下混淆

**Comment by KuFei** [comment]
如果没有其他解决方案就尝试做混淆
